### ISSUE TITLE
error: docker version on mac m1

### ISSUE THREAD

**Issue by materliu** [zu1k/zlib-searcher#23]
```code
[2022-11-30T08:13:01Z INFO  tantivy::directory::file_watcher] Meta file "/index/meta.json" was modified
[2022-11-30T08:13:01Z INFO  actix_web::middleware::logger] 172.19.0.1 "GET /search?limit=100&query= HTTP/1.1" 200 12 "http://localhost:10086/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 1.072605
thread 'actix-rt|system:0|arbiter:2' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownTokenizer { tokenizer: "CANG_JIE", field: "title" }', crates/zlib-searcher-core/src/search.rs:19:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:3' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownTokenizer { tokenizer: "CANG_JIE", field: "title" }', crates/zlib-searcher-core/src/search.rs:19:53
```

as a result, search get nothing, net::ERR_EMPTY_RESPONSE.

**Comment by zu1k** [comment]
download the index version 0.6
